apiVersion: apps/v1
kind: Deployment
metadata:
  name: nav
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nav
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: nav
    spec:
      nodeSelector:
        tools-role: tools
      volumes:
      - name: nav-vol
        persistentVolumeClaim:
          claimName: nav-pvc
      containers:
      - name: nav
        image: ${tag}
        volumeMounts:
        - name: nav-vol
          mountPath: /tqls_system/apps
        ports:
        - name: http
          containerPort: 80
